### ISSUE TITLE
💡 [REQUEST] - Signup, login and authentication

### ISSUE THREAD

**Issue by MalekSmaoui** [CoreTunisia/core-backend#14]
### Summary

Create Signup, login and authentication api

### Basic Example

-Define coach and client behavior.
-Basic signup and and authentication using JWT.

### Priority

❗️ Extreme

### Unresolved questions

-Client and coach attributes.

**Comment by boubakerjouini** [comment]
We are still in the users use cases we will define later the coach or client behaviors once we define them. 
for now the logic is the same even for the profile/modals/nav bars etc...
